version: '3.8'

services:
  next-js:
    image: vavra/project-united_next-js
    container_name: project-united_next-js
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 14.4
    environment: 
      GQL_NETWORK_URL: http://next-js:3000/api/graphql
      GQL_PUBLIC_URL: http://localhost:3000/api/graphql
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
